config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :create]
  resources :wepons, except: [:new, :edit, :update]
  resources :enemies, only: [:update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enemy.rb
class Enemy < ApplicationRecord
  enum kind: [ :goblin, :orc, :demon, :dragon ]

  validates :level, numericality: { greatet_than: 0, less_than_or_equal_to: 99 }
  validates_presence_of :name, :power_base, :power_step, :level, :kind

  def current_power
    power_base + ( ( level - 1 ) * power_step )
  end
end

app/models/user.rb
class User < ApplicationRecord
  enum kind: [:knight, :wizard, :archer, :swordsman]

  validates :level, numericality: { greater_than: 0, less_than_or_equal_to: 99 }
  def title
    "#{ self.kind } #{ self.nickname } ##{ self.level }"
  end
end

app/models/wepon.rb
class Wepon < ApplicationRecord

  validates :level, numericality: { greater_than: 0, less_than_or_equal_to: 90 }
  validates :power_step, numericality: { greater_than: 0, less_than_or_equal_to: 10 }

  def current_power
    (self.power_base + ( ( self.level - 1 ) * self.power_step ) )
  end

  def title
    "#{self.name} ##{self.level}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/enemies_controller.rb
class EnemiesController < ApplicationController
  before_action :set_enemy

  def update
    if @enemy.update(permitted_params)
      render json: @enemy, status: :ok
    else
      render json: { errors: @enemy.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    @enemy.destroy
    head 204
  end
  
  private
  
  def set_enemy
    @enemy = Enemy.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    render json: { message: e.message }, status: :not_found
  end

  def permitted_params
    params.permit(:name, :power_base, :power_step, :level, :kind)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def create
    @user = User.create( permitted_params )
    redirect_to users_path
  end

  private

  def permitted_params
    params.require(:user).permit(:nickname, :kind, :level)
  end
end

app/controllers/wepons_controller.rb
class WeponsController < ApplicationController

  def index
    @wepons = Wepon.all
  end

  def show
    @wepon = Wepon.find_by_id(params[:id])
  end
  
  
  def create
    @wepon = Wepon.new(permitted_params)
    if @wepon.save
      flash[:success] = "Object successfully created"
      redirect_to root_path
    else
      flash[:error] = "Something went wrong"
      render :new
    end
  end

  def destroy
    @wepon = Wepon.find(permitted_params[:id])
    if @wepon.destroy
      flash[:success] = 'Object was successfully deleted.'
      redirect_to root_path
    else
      flash[:error] = 'Something went wrong'
      redirect_to :show
    end
  end
  
  private

  def permitted_params
    params.require(:wepon)
    .permit(:id, :name,:description, :power_base, :power_step, :level )
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RspecApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <p><%= user.title %></p>
<% end %>

app/views/wepons/index.html.erb
<% @wepons.each do |wepon| %>
  <h3> <%= wepon.name %> </h3>
  <p> <%= wepon.current_power %> </p>
  <span> <%= wepon.title %> </span> <br>
  <%= link_to "Show", wepon_path( wepon.id ) %>
<% end %>

app/views/wepons/show.html.erb
<h3> <%=  @wepon.name %> </h3>
<p> <%=  @wepon.description %> </p>
<span> <%=  @wepon.power_base %> </span>
<span> <%=  @wepon.power_step %> </span>
<span> <%=  @wepon.level %> </span>